---
galaxy_info:
  author: Thomas Berton
  description: Role to install Jenkins and install/update plugins
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
  - name: Debian
    versions:
    - wheezy
  categories:
  - development

dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  
